export const UPDATE_ARRIVALS = 'UPDATE_ARRIVALS';
export const START_COFFEE_PARTY = 'START_COFFEE_PARTY';
export const DISMISS_COFFEE_NOTIFICATION = 'DISMISS_COFFEE_NOTIFICATION';
export const SET_NAME = 'SET_NAME';
export const TICK = 'TICK';
