export const DECLARE_ARRIVAL = 'DECLARE_ARRIVAL';
export const START_COFFEE_PARTY = 'START_COFFEE_PARTY';
export const DISMISS_COFFEE_NOTIFICATION = 'DISMISS_COFFEE_NOTIFICATION';
export const SET_NAME = 'SET_NAME';
export const TICK = 'TICK';
