export const UPDATE_ARRIVALS = 'UPDATE_ARRIVALS';
export const UPDATE_COFFEE_TIME = 'UPDATE_COFFEE_TIME';
export const DISMISS_COFFEE_NOTIFICATION = 'DISMISS_COFFEE_NOTIFICATION';
export const SET_NAME = 'SET_NAME';
export const TICK = 'TICK';
